apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 211739080894.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:f24d3928e614f8d6765a6839d21fdc17418718ef
        ports:
        - containerPort: 80
