apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 211739080894.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:07c9c4a02cd03ef07b674272914de79318ed34cf
        ports:
        - containerPort: 80
