apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 211739080894.dkr.ecr.us-west-2.amazonaws.com/shopping-site-earphones:1708db21706723767123a1538fed1c74a81dfdf8
        ports:
        - containerPort: 80
