apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 211739080894.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:07c9c4a02cd03ef07b674272914de79318ed34cf
        ports:
        - containerPort: 80
