apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 211739080894.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:07c9c4a02cd03ef07b674272914de79318ed34cf
        ports:
        - containerPort: 80
