apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 211739080894.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:1708db21706723767123a1538fed1c74a81dfdf8
        ports:
        - containerPort: 80
