apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 211739080894.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlepay:1708db21706723767123a1538fed1c74a81dfdf8
        ports:
        - containerPort: 80
