apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 225962644762.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlepay:95f41f36b4d87723d18b25699055644c966c89d3
        ports:
        - containerPort: 80
