apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 211739080894.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlegrocery:1708db21706723767123a1538fed1c74a81dfdf8
        ports:
        - containerPort: 80
